# Generated by Django 2.1.7 on 2019-03-24 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_companyimg', models.ImageField(upload_to='info/%Y/%m/%D')),
                ('i_companyname', models.CharField(max_length=70)),
                ('i_jobtype', models.CharField(max_length=70)),
                ('i_joblocation', models.CharField(max_length=40)),
                ('i_jobsalary', models.FloatField()),
                ('i_jobdescriptiion', models.TextField(max_length=1000)),
                ('i_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
                ('s_semester', models.IntegerField()),
                ('s_branch', models.CharField(max_length=30)),
                ('s_tenthmarks', models.FloatField()),
                ('s_twelthmarks', models.FloatField()),
                ('s_currentcgpa', models.FloatField()),
                ('s_skills', models.CharField(max_length=100)),
                ('s_proglang', models.CharField(max_length=300)),
                ('s_mobno', models.IntegerField(max_length=13)),
                ('s_resume1', models.FileField(upload_to='resume/%Y/%m/%D')),
                ('s_resume2', models.FileField(upload_to='resume/%Y/%m/%D')),
            ],
        ),
    ]
