# Generated by Django 2.1.7 on 2019-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_mobno',
            field=models.IntegerField(),
        ),
    ]
