# Generated by Django 2.1.7 on 2019-03-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_info_i_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='i_proglang',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='i_skills',
            field=models.CharField(default='learning', max_length=500),
            preserve_default=False,
        ),
    ]
