# Generated by Django 2.1.7 on 2019-03-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190325_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='i_jobdescriptiion',
            field=models.TextField(max_length=2000),
        ),
    ]
