# Generated by Django 2.1.7 on 2019-03-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20190325_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_resume1',
            field=models.FileField(default='media/noresume.pdf', upload_to='resume/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_resume2',
            field=models.FileField(default='media/noresume.pdf', upload_to='resume/%Y/%m/%D'),
        ),
    ]
