# Generated by Django 2.1.7 on 2019-03-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20190325_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='s_username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
