# Generated by Django 2.1.7 on 2019-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20190325_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_mobno',
            field=models.CharField(max_length=13),
        ),
    ]
