# Generated by Django 2.1.7 on 2019-03-25 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20190325_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_mobno',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
