# Generated by Django 2.1.7 on 2019-03-25 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20190325_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_mobno',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
