# Generated by Django 2.1.7 on 2019-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20190325_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_resume1',
            field=models.FileField(default='resume/BRAJESH3.pdf', upload_to='resume/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_resume2',
            field=models.FileField(default='resume/BRAJESH3.pdf', upload_to='resume/%Y/%m/%D'),
        ),
    ]
